package uz.vv.product

enum class ErrorCode(val code: Int) {
    PRODUCT_NOT_FOUND(1001),
    PRODUCT_ALREADY_EXISTS(1002),

    CATEGORY_NOT_FOUND(2001),
    CATEGORY_ALREADY_EXISTS(2002),
    CATEGORY_HAS_CHILDREN(2003),
    CATEGORY_HAS_PRODUCTS(2004),
    CATEGORY_CIRCULAR_REFERENCE(2005),

    INVALID_REQUEST(3001),

    DATABASE_SEQUENCE_ERROR(9999),
}